# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - reactaplikacija

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://acrreactapp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_79a092e655204a13bed2db21a644bb06 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_aa90a770b7be408eb64e80791df62749 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: acrreactapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_79a092e655204a13bed2db21a644bb06 }}/reactwebapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'reactaplikacija'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_62132923a03c4bd78e08b92317fcea26 }}
        images: 'acrreactapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_79a092e655204a13bed2db21a644bb06 }}/reactwebapp:${{ github.sha }}'